spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  profiles:
    include: oauth
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb # test ??? ??? ??? ??? ???? ???.
    username: sa # username? password? ??? ??? ??
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # ??????? ??? ? ??????? ????? ?? ??? ??
    properties:
      hibernate:
        format_sql: true # ???? query? ???

logging.level:
  org.hibernate.SQL: debug
